name: Build driver solution
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]
    runs-on: windows-2022
    env:
      Solution_Path: driver.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: |
          msbuild ${{ env.Solution_Path }} /property:Configuration=${{ env.Configuration }} /property:Platform=${{ env.Platform }} 

        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      - name: Build result
        run: |
          cd ${{ matrix.platform }}/${{ matrix.configuration }}
          dir

      - name: Archive
        run: |
          Compress-Archive ${{ matrix.platform }}/${{ matrix.configuration }} ${{ matrix.configuration }}.zip

      - name: Release build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}Build
          path: ${{ matrix.configuration }}.zip