name: Build driver solution
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]
    runs-on: windows-2022
    env:
      Solution_Path: driver.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: |
          msbuild ${{ env.Solution_Path }} /property:Configuration=${{ env.Configuration }} /property:Platform=${{ env.Platform }} 

#-p:Configuration:${{ env.Configuration }} -p:Platform:${{ env.Platform }}

        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      - name: Test
        run: |
          cd ${{ env.Platform }}/${{ env.Configuration }}
          ls

#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            book.zip
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}